Schemas Partner
projetoKhali/api4front pull request #17
Opened 2024-04-12 23:38 UTC by ryanlanziloti

resolve #11
# Objetivo:
`Qual o propósito / escopo dessas alterações?`
Adcionar schemas do partner
- 

# Solução:
`Quais estratégias foram adotadas durante as alterações em questão?`

- 

# Pendências:
`Pendências notáveis referentes ao escopo dessas alterações que continuam em aberto.`

- 

# Prosseguimento:
`Possíveis caminhos a seguir para solucionar as pendências mencionadas.`

-

2024-04-12 23:44 UTC, paulo-granthon requested changes

2024-04-12 23:44 UTC, paulo-granthon commented on src/schemas/PartnerTrack.ts
> +    expertises: PartnerExpertiseSchema
Aqui tem que ser uma lista / array pq uma Expertise contém multiplos Qualifiers

A mesma coisa se aplica a todas as outras instâncias aonde você referencia outro schema como valor de um atributo; Em todos os casos deve ser lista 

```suggestion
    expertises: PartnerExpertiseSchema[]
```

2024-04-13 19:58 UTC, paulo-granthon approved these changes, later dismissed

2024-04-13 21:35 UTC, Incivius submitted a review, later dismissed

2024-04-13 23:01 UTC, Incivius approved these changes

2024-04-14 00:02 UTC, paulo-granthon approved these changes

2024-04-14 00:08 UTC, merged