Componentes do Produto
projetoKhali/api4front pull request #19
Opened 2024-04-13 04:26 UTC by JhonatanLop

# Objetivo:
`Qual o propósito / escopo dessas alterações?`

- crição de componentes para visualização de informações.

# Solução:
`Quais estratégias foram adotadas durante as alterações em questão?`

- a criação do componente "card" que possui um texto e um número
- a crição de um componente tabela

# Pendências:
`Pendências notáveis referentes ao escopo dessas alterações que continuam em aberto.`

- Possíveis pendências:
1. scroll bar
2. finalização de estilo
3. modularizar a tabela.
> modularizar a tabela melhora a forma como ela pode ser implantada sem necessidade de alteração no código.

# Prosseguimento:
`Possíveis caminhos a seguir para solucionar as pendências mencionadas.`

-

2024-04-13 20:00 UTC, paulo-granthon requested changes

2024-04-13 20:00 UTC, paulo-granthon commented on views/App.vue
> +  <CountCard titulo="Total de parceiros" :numero="9.856"></CountCard>
esse componente não está configurado para utilizar parâmetros, os valores estão hardcoded

2024-04-13 21:46 UTC, paulo-granthon approved these changes

2024-04-13 21:49 UTC, paulo-granthon requested changes

2024-04-13 21:49 UTC, paulo-granthon commented on views/App.vue
esse arquivo aparenta ter sido movido de `src/` para `src/views/`. o arquivo `App.vue` fica em `src/` mesmo

2024-04-14 05:30 UTC, markusgomes submitted a review, later dismissed

2024-04-14 14:21 UTC, Incivius approved these changes, later dismissed

2024-04-14 15:00 UTC, paulo-granthon approved these changes

2024-04-14 15:56 UTC, Incivius approved these changes

2024-04-14 17:09 UTC, merged