Service fix
projetoKhali/api4front pull request #49
Opened 2024-04-25 01:30 UTC by Incivius

# Objetivo:
`Qual o propósito / escopo dessas alterações?`

- Arrumar o mapeamento dos dados dentro dos service dos dashboard

# Solução:
`Quais estratégias foram adotadas durante as alterações em questão?`

- Tipar os dados utilizando os schemas;

- resolve #47

2024-04-25 13:18 UTC, NicSouza approved these changes, later dismissed

2024-04-25 14:15 UTC, paulo-granthon requested changes
falta rodar um `lint:fix`

2024-05-01 01:52 UTC, paulo-granthon approved these changes

2024-05-02 20:10 UTC, NicSouza approved these changes

2024-05-03 18:56 UTC, merged