List users partner
projetoKhali/api4front pull request #62
Opened 2024-05-06 02:26 UTC by Incivius

### Você rodou o comando `yarn lint:fix` *ou* `npm run lint:fix` antes de abrir o PR?
`Se não, rode o comando e faça um novo commit incluindo as correções resultantes.`

- [ ] Sim
- [x] Não

# Objetivo:
`Qual o propósito / escopo dessas alterações?`

- Criação da lista de user and Partner
- - resolve #55 

# Solução:
`Quais estratégias foram adotadas durante as alterações em questão?`

- 

# Pendências:
`Pendências notáveis referentes ao escopo dessas alterações que continuam em aberto.`

- 

# Prosseguimento:
`Possíveis caminhos a seguir para solucionar as pendências mencionadas.`

-

2024-05-06 02:29 UTC, lucasjonathangomes approved these changes, later dismissed

2024-05-06 04:39 UTC, paulo-granthon requested changes

2024-05-06 04:39 UTC, paulo-granthon commented on yarn.lock
acabou entrando um `yarn.lock` aqui :/

2024-05-07 02:03 UTC, paulo-granthon submitted a review, later dismissed

2024-05-07 23:06 UTC, taniacruzz approved these changes, later dismissed

2024-05-09 02:47 UTC, paulo-granthon approved these changes, later dismissed

2024-05-09 03:07 UTC, taniacruzz approved these changes, later dismissed

2024-05-09 20:29 UTC, paulo-granthon approved these changes

2024-05-09 20:31 UTC, NicSouza approved these changes

2024-05-09 20:47 UTC, merged