Service trackmetrics
projetoKhali/api4front pull request #86
Opened 2024-05-16 01:46 UTC by lucasjonathangomes

### Você rodou o comando `yarn lint:fix` *ou* `npm run lint:fix` antes de abrir o PR?
`Se não, rode o comando e faça um novo commit incluindo as correções resultantes.`

- [x] Sim
- [ ] Não

# Objetivo:
`Qual o propósito / escopo dessas alterações?`

-Nova tool para service de Track service

2024-05-16 04:44 UTC, paulo-granthon requested changes
ao efetuar o merge com o branch `dev` no commit e478cae584e4ef1d5c83b3bedf5cd58ddc3a389b, as alterações feitas nos seguintes arquivos foram perdidas:
- [`.eslintrc.yml`](https://github.com/projetoKhali/api4front/pull/86/files#diff-9e1ecc14c733bb1ae2e523089f1262ac6ffccbcf950487ee0984403603550e57)
- [`,markdownlint.yml`](https://github.com/projetoKhali/api4front/pull/86/files#diff-064fdcba936d5758a9cfb53350ba82091401d11ca38773bb294bdeb638d4c465)
- [`index.html`](https://github.com/projetoKhali/api4front/pull/86/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051)

2024-05-17 03:26 UTC, paulo-granthon commented
e478cae584e4ef1d5c83b3bedf5cd58ddc3a389b

2024-05-17 03:48 UTC, paulo-granthon approved these changes

2024-05-17 15:13 UTC, Incivius approved these changes

2024-05-18 16:39 UTC, merged