Multipleselectfilter
projetoKhali/api4front pull request #87
Opened 2024-05-18 15:13 UTC by NicSouza

### Você rodou o comando `yarn lint:fix` *ou* `npm run lint:fix` antes de abrir o PR?
`Se não, rode o comando e faça um novo commit incluindo as correções resultantes.`

- [x] Sim
- [ ] Não

# Objetivo:
`Qual o propósito / escopo dessas alterações?`

- Criar o componente filtro de seleção de partner

# Solução:
`Quais estratégias foram adotadas durante as alterações em questão?`

- Utilizei do PrimeVue para criar o componente.

# Pendências:
`Pendências notáveis referentes ao escopo dessas alterações que continuam em aberto.`

- 

# Prosseguimento:
`Possíveis caminhos a seguir para solucionar as pendências mencionadas.`

-

2024-05-18 15:24 UTC, Incivius approved these changes

2024-05-18 16:41 UTC, lucasjonathangomes approved these changes

2024-05-18 19:27 UTC, paulo-granthon requested changes
Não consegui

2024-05-18 19:27 UTC, paulo-granthon commented on src/main.ts
> +import PrimeVue from 'primevue/config';
não consegui executar, mesmo após instalar as dependências através do comando `yarn`, existe algum outro setup adicional que precisa ser feito para executar a aplicação?
![2024_05_18_16:25:35_sshot](https://github.com/projetoKhali/api4front/assets/93501477/4b1f1d3a-74b8-49f7-88b6-c6ad20bafcb0)

2024-05-18 19:33 UTC, paulo-granthon commented on src/main.ts
> +import PrimeVue from 'primevue/config';
Ah, faltou adicionar as alterações do `package.json` e `yarn.lock` resultantes do `yarn add primevue`
![2024_05_18_16:32:04_sshot](https://github.com/projetoKhali/api4front/assets/93501477/c67cbb0d-c569-4b03-993f-842a635556e6)

2024-05-18 21:24 UTC, paulo-granthon approved these changes

2024-05-18 21:55 UTC, Incivius approved these changes

2024-05-21 00:16 UTC, Incivius approved these changes

2024-05-21 01:07 UTC, paulo-granthon approved these changes

2024-05-21 20:01 UTC, lucasjonathangomes approved these changes

2024-05-21 20:28 UTC, Incivius approved these changes

2024-05-21 23:58 UTC, JhonatanLop approved these changes

2024-05-22 21:53 UTC, paulo-granthon approved these changes

2024-05-22 22:04 UTC, lucasjonathangomes approved these changes
✅

2024-05-23 17:58 UTC, merged